[client]
# toolbarMode = "minimal"

[server]
headless = true
runOnSave = true
maxUploadSize = 2

[theme]
# Base and font
base                          = "dark"
font                          = "sans-serif"
baseFontSize                  = 17
baseFontWeight                = 400
headingFont                   = "sans-serif"
headingFontSizes              = ["2.5rem", "2rem", "1.75rem", "1.5rem", "1.25rem", "1rem"]
headingFontWeights            = [700, 600, 600, 500, 500, 500]
codeFont                      = "monospace"
codeFontSize                  = "1rem"
codeFontWeight                = 400

# Color palette - One UI-inspired
primaryColor                  = "#71AFFF"    # Soft blue (primary accent)
backgroundColor               = "#0E1621"    # Main dark background
secondaryBackgroundColor      = "#1A2533"    # Cards/panels
textColor                     = "#F1F4F7"    # High contrast white
linkColor                     = "#FFD361"    # Warm pastel yellow
linkUnderline                 = false
codeBackgroundColor           = "#101B2A"    # Code box
borderColor                   = "#2A3A4B"    # Flat muted border
dataframeBorderColor          = "#2A3A4B"
dataframeHeaderBackgroundColor = "#1E2C3C"

# UI Design
baseRadius                    = "1.25rem"     # Large and modern
buttonRadius                  = "2.5rem"
showWidgetBorder              = false
showSidebarBorder             = false

# Charts - consistent soft tones
chartCategoricalColors = [
  "#71AFFF",  # accent blue
  "#FFC971",  # soft orange
  "#7ED6C0",  # mint green
  "#FF9A8B",  # warm salmon
  "#CBA5FF"   # lavender
]

chartSequentialColors = [
  "#0C131B", "#18212B", "#223045", "#2C4260", "#3C5E80",
  "#4F7FB0", "#71AFFF", "#A4CEFF", "#D4EBFF", "#F2F9FF"
]

[theme.sidebar]
# Fonts and layout
font                          = "sans-serif"
headingFont                   = "sans-serif"
headingFontSizes              = ["1.75rem", "1.5rem", "1.25rem", "1.125rem", "1rem", "0.875rem"]
headingFontWeights            = [700, 600, 600, 500, 500, 500]
codeFont                      = "monospace"
codeFontSize                  = "1rem"

# Sidebar coloring
primaryColor                  = "#71AFFF"
backgroundColor               = "#0A121A"
secondaryBackgroundColor      = "#18212B"
textColor                     = "#F1F4F7"
linkColor                     = "#FFD361"
linkUnderline                 = false
codeBackgroundColor           = "#101B2A"
borderColor                   = "#2A3A4B"
dataframeBorderColor          = "#2A3A4B"
dataframeHeaderBackgroundColor = "#1E2C3C"

# Sidebar layout
baseRadius                    = "1.25rem"
buttonRadius                  = "2.5rem"
showWidgetBorder              = false