[client]
# toolbarMode = "minimal"

[server]
headless = true
runOnSave = true
maxUploadSize = 2

[theme]
base = "dark"
primaryColor = "#61AFEF"
backgroundColor = "#282C34"
secondaryBackgroundColor = "#21252B"
textColor = "#E6E6E6"
linkColor = "#56B6C2"
codeBackgroundColor = "#2C313C"
font = "sans-serif"
codeFont = "monospace"
headingFont = "sans-serif"
baseRadius = "0.4rem"
borderColor = "#3A3F4B"
showWidgetBorder = true
baseFontSize = 16
showSidebarBorder = false

[theme.sidebar]
primaryColor = "#61AFEF"
backgroundColor = "#21252B"
secondaryBackgroundColor = "#2C313C"
textColor = "#ECECEC"
linkColor = "#56B6C2"
codeBackgroundColor = "#2C313C"
font = "sans-serif"
codeFont = "monospace"
headingFont = "sans-serif"
baseRadius = "0.4rem"
borderColor = "#3A3F4B"
showWidgetBorder = true